// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, body, user_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)
RETURNING id, body, user_id, created_at, updated_at
`

type CreatePostParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Body, arg.UserID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostByID = `-- name: DeletePostByID :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePostByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePostByID, id)
	return err
}

const editPostBodyByID = `-- name: EditPostBodyByID :exec
UPDATE posts
SET 
    body = $1,
    updated_at = NOW()
WHERE user_id = $2
`

type EditPostBodyByIDParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) EditPostBodyByID(ctx context.Context, arg EditPostBodyByIDParams) error {
	_, err := q.db.ExecContext(ctx, editPostBodyByID, arg.Body, arg.UserID)
	return err
}

const getAllPostsByID = `-- name: GetAllPostsByID :many
SELECT id, body, user_id, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetAllPostsByID(ctx context.Context, id uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPostsByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, body, user_id, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
